{% set version = "0.4.1" %}

package:
  name: vale-styles-write-good
  version: {{ version }}

source:
  - folder: write-good
    fn: vale-write-good-0.4.0.zip
    url: https://github.com/errata-ai/write-good/releases/download/v{{ version }}/write-good.zip
    sha256: 2960ef10861ddc7dc76292a4967eb3789bf05ca24f862042f6d15f53332887f0
  - fn: LICENSE-vale-write-good-0.4.0
    url: https://raw.githubusercontent.com/errata-ai/write-good/v{{ version }}/LICENSE
    sha256: b9bb0975e308708b97e4a30c7665c815fe4bd3a1de2ed04d35c0eef03d4eaa69

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/write-good
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: write-good rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
